### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by lemonmojo** [royalapplications/openh264#1]
- [x] Get rid of the dylibs and keep just the static lib
- [x] lipo arm64/x86_64 binaries
- [x] Make XCFramework out of static libs
- [x] codesign XCFramework
- [x] Maybe get rid of the headers in the XCFramework, I don't think we need them
- [x] Test compiling FreeRDP
- [x] Test compiling FreeRDPKit
